version: '3.1'

services:
  api:
    build:
      context: wildfly
    ports:
        - 8080:8080
        - 9990:9990

  db:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_DATABASE: dbmovie
      MYSQL_USER: movie
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  dbdata:

